// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokAsset, StoryblokMultilink, StoryblokMultiasset } from '../storyblok.d.ts';
export interface Action {
  label: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"}>;
  external?: boolean;
  button?: boolean;
  color?: "" | "primary" | "secondary";
  id?: string;
  component: "action";
  _uid: string;
  [k: string]: unknown;
}

export interface Alias {
  title?: string;
  image?: StoryblokAsset;
  resource: "next-event" | "last-article";
  filter?: string;
  submit?: Form[];
  component: "alias";
  _uid: string;
  [k: string]: unknown;
}

export interface Article {
  alias?: ISbStoryData<Article> | string;
  new?: unknown;
  title?: string;
  description?: string;
  image?: StoryblokAsset;
  author?: ISbStoryData<Person> | string;
  body?: (Section | Carousel | Aside)[];
  hidden?: boolean;
  component: "article";
  _uid: string;
  [k: string]: unknown;
}

export interface Aside {
  id?: string;
  enrollment?: unknown;
  amount?: string;
  steps?: string;
  discount?: string;
  due_date?: string;
  courses?: (ISbStoryData<Course> | string)[];
  forms: Form[];
  contents: (Process | Text | Action | Wrapper | Alias)[];
  theme?: "" | "dark";
  component: "aside";
  _uid: string;
  [k: string]: unknown;
}

export interface Background {
  image?: StoryblokAsset;
  video?: string;
  position?: ("" | "right" | "center" | "left")[];
  author?: ISbStoryData<Person> | string;
  component: "background";
  _uid: string;
  [k: string]: unknown;
}

export interface Business {
  title: string;
  logo?: StoryblokAsset;
  contact_person?: string;
  email?: string;
  area?: "" | "interior" | "fashion";
  component: "business";
  _uid: string;
  [k: string]: unknown;
}

export interface Carousel {
  interface?: boolean;
  id?: string;
  slides: (Section | Wrapper | Person | Image)[];
  weight?: "" | "none" | "low" | "high";
  view?: string;
  delay?: string;
  order?: string;
  component: "carousel";
  _uid: string;
  [k: string]: unknown;
}

export interface Course {
  alias?: ISbStoryData<Course> | string;
  new?: unknown;
  id?: string;
  title?: string;
  location?: ISbStoryData<Location> | string;
  days?: ("" | "Lunedì" | "Martedi" | "Mercoledì" | "Giovedì" | "Venerdì" | "Sabato")[];
  hours?: ("" | "9:00/12:00" | "13:00/16:00" | "20:00/23:00")[];
  starts?: string;
  ends?: string;
  seats?: string;
  page?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "course";
  _uid: string;
  [k: string]: unknown;
}

export interface Event {
  alias?: ISbStoryData<Event> | string;
  new?: unknown;
  title?: string;
  description?: string;
  openday?:
    | ""
    | "interni - primo livello"
    | "interni - secondo livello"
    | "moda - primo livello"
    | "moda - secondo livello";
  location?: ISbStoryData<Location> | string;
  date?: string;
  page?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  form?: ISbStoryData<Form> | string;
  component: "event";
  _uid: string;
  [k: string]: unknown;
}

export interface Field {
  id: string;
  input: "text" | "number" | "email" | "tel" | "date" | "checkbox" | "area" | "select" | "multiple" | "enroll";
  hidden?: boolean;
  label: string;
  placeholder?: string;
  required?: boolean;
  options?: string;
  component: "field";
  _uid: string;
  [k: string]: unknown;
}

export interface Form {
  alias?: ISbStoryData<Form> | string;
  action?: "" | "/api/jobs" | "/api/company";
  list?: ("" | 31 | 32 | 25 | 26 | 35 | 16 | 15 | 17 | 28 | 19 | 30 | 33 | 24 | 29 | "23")[];
  tracking?: "" | "enroll" | "open_day" | "download" | "project" | "recruit" | "partnership";
  new?: unknown;
  title?: string;
  label?: string;
  fields?: Field[];
  message?: string;
  terms?: string;
  component: "form";
  _uid: string;
  [k: string]: unknown;
}

export interface Gallery {
  fullScreen?: boolean;
  interface?: boolean;
  delay?: string;
  images: StoryblokMultiasset;
  size?: "" | "1/2" | "1/4" | "1/8";
  aspect?: "" | "1/1" | "3/4" | "4/3";
  width?: ("" | "1/4" | "1/3" | "1/2" | "2/3" | "3/4" | "1/1")[];
  component: "gallery";
  _uid: string;
  [k: string]: unknown;
}

export interface Grid {
  resource?: "" | "articles" | "persons" | "jobs" | "courses" | "events" | "projects";
  title?: string;
  subtitle?: string;
  filter?: string;
  columns?: string;
  limit?: string;
  dark?: boolean;
  component: "grid";
  _uid: string;
  [k: string]: unknown;
}

export interface Image {
  image: StoryblokAsset;
  width?: ("" | "1/4" | "1/3" | "1/2" | "2/3" | "3/4" | "1/1")[];
  size?: "" | "sm" | "md" | "lg";
  aspect?: "" | "1/1" | "3/4" | "4/9" | "4/3" | "9/4";
  order?: string;
  fullScreen?: boolean;
  author?: ISbStoryData<Person> | string;
  component: "image";
  _uid: string;
  [k: string]: unknown;
}

export interface Job {
  company: string;
  business?: string;
  logo?: StoryblokAsset;
  area?: "" | "interior" | "fashion";
  title?: string;
  description?: string;
  location?: string;
  component: "job";
  _uid: string;
  [k: string]: unknown;
}

export interface List {
  items: Text[];
  size?: "" | "1/4" | "1/3" | "1/2" | "2/3" | "3/4";
  component: "list";
  _uid: string;
  [k: string]: unknown;
}

export interface Location {
  alias?: ISbStoryData<Location> | string;
  new?: unknown;
  title?: string;
  address?: string;
  gps?: string;
  direction?: string;
  component: "location";
  _uid: string;
  [k: string]: unknown;
}

export interface Map {
  locations: (ISbStoryData<Location> | string)[];
  component: "map";
  _uid: string;
  [k: string]: unknown;
}

export interface Menu {
  title?: string;
  links: Action[];
  inline?: boolean;
  component: "menu";
  _uid: string;
  [k: string]: unknown;
}

export interface Nav {
  contents?: (Action | List | Menu)[];
  message?: string;
  component: "nav";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  auth?: boolean;
  preview?: unknown;
  title?: string;
  description?: string;
  image?: StoryblokAsset;
  menu?: unknown;
  header?: ISbStoryData<Nav> | string;
  footer?: ISbStoryData<Nav> | string;
  body?: (Section | Carousel | Map | Aside | Grid)[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Person {
  alias?: ISbStoryData<Person> | string;
  hide?: ("" | "video" | "description" | "role" | "links" | "image" | "title")[];
  new?: unknown;
  image?: StoryblokAsset;
  video?: string;
  title?: string;
  role?: "" | "interior" | "style" | "design" | "cad" | "3d" | "building" | "lighting";
  description?: string;
  links?: Action[];
  component: "person";
  _uid: string;
  [k: string]: unknown;
}

export interface Process {
  steps: Wrapper[];
  component: "process";
  _uid: string;
  [k: string]: unknown;
}

export interface Project {
  body?: (Carousel | Form | Grid | Map | Nav | Section)[];
  cover: StoryblokAsset;
  title: string;
  subtitle: string;
  component: "project";
  _uid: string;
  [k: string]: unknown;
}

export interface Section {
  id?: string;
  contents: (
    | Alias
    | Background
    | Image
    | Gallery
    | Video
    | List
    | Process
    | Text
    | Action
    | Wrapper
    | Carousel
    | Location
    | Person
    | Event
    | Course
    | Article
    | Form
  )[];
  align?: ("" | "start" | "center" | "end" | "stretch")[];
  dark?: boolean;
  component: "section";
  _uid: string;
  [k: string]: unknown;
}

export interface Text {
  title?: string;
  description?: string;
  justify?: "" | "right" | "center" | "left";
  width?: ("" | "1/4" | "1/3" | "1/2" | "2/3" | "3/4" | "1/1")[];
  theme?: "" | "primary" | "secondary" | "dark" | "light";
  order?: string;
  hide?: "" | "title" | "description" | "all";
  component: "text";
  _uid: string;
  [k: string]: unknown;
}

export interface Video {
  source: string;
  width?: ("" | "1/4" | "1/3" | "1/2" | "2/3" | "3/4" | "1/1")[];
  order?: string;
  component: "video";
  _uid: string;
  [k: string]: unknown;
}

export interface Wrapper {
  contents: (
    | Image
    | Video
    | Gallery
    | Background
    | Text
    | Action
    | List
    | Menu
    | Map
    | Course
    | Person
    | Event
    | Form
    | Carousel
    | Location
    | Wrapper
  )[];
  row?: boolean;
  width?: ("" | "1/4" | "1/3" | "1/2" | "2/3" | "3/4" | "1/1")[];
  justify?: "" | "right" | "center" | "left";
  order?: string;
  component: "wrapper";
  _uid: string;
  [k: string]: unknown;
}

export type ContentType = Article | Business | Course | Event | Form | Job | Location | Nav | Page | Person | Project;
